// start-server.js
// Custom entrypoint for Next.js standalone mode to ensure it binds to all interfaces (0.0.0.0)
// This is required for Docker and Railway deployments.

process.env.HOSTNAME = '0.0.0.0';
process.env.PORT = process.env.PORT || 3000;

console.log(`Starting Next.js standalone server on ${process.env.HOSTNAME}:${process.env.PORT}...`);

// The standalone server is generated by Next.js in the .next/standalone directory
require('./.next/standalone/server.js');
