"""
sync_docs.py — Auto-sync all documentation with the current live portfolio.

Run manually:  python -m scripts.sync_docs
Git hook:       automatically runs before every commit via .git/hooks/pre-commit

What it does:
  1. Reads PORTFOLIO_V4 from src/strategies/portfolio_v4.py (source of truth)
  2. Runs a 30-day quick backtest to get current PF/WR numbers
  3. Rewrites the AUTOGENERATED blocks in:
     - docs/REPO_GUIDE.md         (§3 live config table)
     - docs/plans/DAILY_BATTLE_PLAN.md  (Live Configuration block)
     - docs/research/STRATEGY_REGISTRY.md  (Active legs table)
  4. Prints a diff summary of what changed.
"""

from __future__ import annotations
import re
import sys
import os
import inspect
from datetime import datetime, timezone, timedelta
from pathlib import Path
import numpy as np

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

REPO_ROOT = Path(__file__).parent.parent
START_MARKER = "<!-- AUTOGENERATED:LIVE_CONFIG_START -->"
END_MARKER   = "<!-- AUTOGENERATED:LIVE_CONFIG_END -->"

# ── helpers ───────────────────────────────────────────────────────────────────

def _ts(d: str) -> int:
    return int(datetime.strptime(d, "%Y-%m-%d").replace(tzinfo=timezone.utc).timestamp())

def replace_block(path: Path, new_content: str) -> bool:
    """Replace text between AUTOGENERATED markers. Returns True if file changed."""
    text = path.read_text(encoding="utf-8")
    pattern = re.compile(
        re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER),
        re.DOTALL,
    )
    replacement = f"{START_MARKER}\n{new_content.strip()}\n{END_MARKER}"
    new_text, count = pattern.subn(replacement, text)
    if count == 0:
        print(f"  ⚠️  No AUTOGENERATED block found in {path.name} — skipping")
        return False
    if new_text == text:
        print(f"  ✅ {path.name} already up-to-date")
        return False
    path.write_text(new_text, encoding="utf-8")
    print(f"  ✏️  Updated {path.name}")
    return True


# ── strategy introspection ────────────────────────────────────────────────────

def get_portfolio_meta() -> list[dict]:
    """Import PORTFOLIO_V4 and extract metadata from each strategy class."""
    sys.path.insert(0, str(REPO_ROOT))
    from src.strategies.portfolio_v4 import PORTFOLIO_V4
    legs = []
    for cls in PORTFOLIO_V4:
        inst = cls()
        legs.append({
            "name":    getattr(inst, "name",    cls.__name__),
            "magic":   getattr(inst, "magic",   "?"),
            "sl_atr":  getattr(inst, "sl_atr_mult", "?"),
            "tp_atr":  getattr(inst, "tp_atr_mult", "?"),
            "cls":     cls,
        })
    return legs


# ── quick backtest ────────────────────────────────────────────────────────────

def run_30day_backtest(legs_meta: list[dict]) -> dict:
    """Run a 30-day fixed-lot backtest and return summary stats."""
    try:
        from src.backtesting.data import load_bars
        from src.backtesting.engine import BacktestEngine, EngineConfig
        from src.backtesting.costs import SCENARIOS
        from src.strategies.portfolio_v4 import PORTFOLIO_V4

        bars = load_bars("XAUUSDm", timeframes=("M15", "M5", "M1", "D1"))

        end_dt   = datetime.now(timezone.utc)
        start_dt = end_dt - timedelta(days=30)
        end_ts   = int(end_dt.timestamp())
        start_ts = int(start_dt.timestamp())

        cfg = EngineConfig(
            symbol="XAUUSDm",
            starting_balance=100.0,
            sizing_mode="fixed",
            fixed_lots=0.01,
            dedup_per_candle=True,
            max_concurrent=2,
            max_same_direction=2,
            enable_pyramiding=False,
            enable_consolidation_exit=False,
            enable_trailing=False,
            history_bars=250,
            warmup_bars=300,
            daily_loss_limit_mode="off",
            enable_d1_bias_gate=True,
            direction_gate="d1_ema20",
        )

        eng = BacktestEngine(bars=bars, cost=SCENARIOS["realistic"], config=cfg)
        res = eng.run([cls() for cls in PORTFOLIO_V4], start_ts=start_ts, end_ts=end_ts)

        IST = 5.5 * 3600
        balance = 100.0
        daily_pl, daily_start_bal, shutdown_days, kept = {}, {}, set(), []

        for t in sorted(res.trades, key=lambda t: t.exit_time):
            day = datetime.fromtimestamp(t.entry_time + IST, tz=timezone.utc).date()
            if day not in daily_start_bal:
                daily_start_bal[day] = balance
            if day in shutdown_days:
                continue
            balance += t.net_pl
            daily_pl[day] = daily_pl.get(day, 0.0) + t.net_pl
            kept.append(t)
            if daily_pl[day] < -0.06 * daily_start_bal[day]:
                shutdown_days.add(day)

        # Per-strategy stats
        by_strat: dict[str, list] = {}
        for t in kept:
            by_strat.setdefault(t.strategy, []).append(t.net_pl)

        net = np.array([t.net_pl for t in kept])
        wins = net[net > 0]
        losses = net[net < 0]
        pf = float(wins.sum() / -losses.sum()) if len(losses) > 0 else float("inf")
        wr = float(len(wins) / len(net) * 100) if len(net) > 0 else 0.0

        strat_stats = {}
        for sname, pnls in by_strat.items():
            arr = np.array(pnls)
            w = arr[arr > 0]; l = arr[arr < 0]
            strat_stats[sname] = {
                "trades": len(arr),
                "wr": float(len(w) / len(arr) * 100) if len(arr) > 0 else 0,
                "pf": float(w.sum() / -l.sum()) if len(l) > 0 else float("inf"),
                "net_pl": float(arr.sum()),
            }

        return {
            "ok": True,
            "start": start_dt.strftime("%Y-%m-%d"),
            "end": end_dt.strftime("%Y-%m-%d"),
            "trades": len(kept),
            "wr": wr,
            "pf": pf,
            "net_pl": float(net.sum()) if len(net) > 0 else 0.0,
            "end_bal": balance,
            "by_strat": strat_stats,
        }
    except Exception as e:
        print(f"  ⚠️  30-day backtest failed: {e}")
        return {"ok": False}


# ── document generators ───────────────────────────────────────────────────────

def _session_for(name: str) -> str:
    n = name.upper()
    if "LONDON" in n or "EMASTACK" in n:
        return "11:30–15:30"
    return "17:30–21:30"

def gen_repo_guide_block(legs: list[dict], bt: dict) -> str:
    today = datetime.now().strftime("%Y-%m-%d")
    rows = "\n".join(
        f"| `{l['name']}` | {l['magic']} | {_session_for(l['name'])} | "
        f"{l['sl_atr']} / {l['tp_atr']} | |"
        for l in legs
    )
    bt_line = ""
    if bt.get("ok"):
        pf_s = f"{bt['pf']:.2f}" if bt["pf"] < 99 else "∞"
        sign = "+" if bt["net_pl"] >= 0 else ""
        bt_line = (
            f"\n**Last-30-day snapshot** ({bt['start']} → {bt['end']}): "
            f"{bt['trades']} trades · {bt['wr']:.1f}% WR · PF {pf_s} · "
            f"{sign}${bt['net_pl']:.2f} net."
        )
    return f"""`main_loop` runs **`PORTFOLIO_V4`** from `src/strategies/portfolio_v4.py`
_(last synced {today} by `scripts/sync_docs.py`)_:

| Leg | Magic | Session IST | SL/TP ×ATR | Notes |
|---|---|---|---|---|
{rows}
{bt_line}"""


def gen_battle_plan_block(legs: list[dict], bt: dict) -> str:
    today = datetime.now().strftime("%Y-%m-%d")
    rows = "\n".join(
        f"| {l['name']} | {_session_for(l['name'])} | {l['sl_atr']} / {l['tp_atr']} |"
        for l in legs
    )
    bt_line = ""
    if bt.get("ok"):
        pf_s = f"{bt['pf']:.2f}" if bt["pf"] < 99 else "∞"
        sign = "+" if bt["net_pl"] >= 0 else ""
        bt_line = (
            f"\n**Last-30-day:** {bt['trades']} trades · {bt['wr']:.1f}% WR · "
            f"PF {pf_s} · {sign}${bt['net_pl']:.2f}"
        )
    return f"""The bot currently runs **PORTFOLIO_V4** (updated {today}):

| Leg | Session (IST) | SL / TP (×ATR) |
|---|---|---|
{rows}
{bt_line}"""


def gen_strategy_registry_block(legs: list[dict], bt: dict) -> str:
    today = datetime.now().strftime("%Y-%m-%d")
    rows = []
    for l in legs:
        sname = l["name"]
        st = bt.get("by_strat", {}).get(sname, {})
        if st:
            pf_s = f"{st['pf']:.2f}" if st["pf"] < 99 else "∞"
            grade = "✅ B" if st["pf"] >= 1.2 else "⚠️ C"
            rows.append(
                f"| {sname} | {l['magic']} | {_session_for(sname)} | "
                f"{grade} | 30d: {st['trades']}T · {st['wr']:.1f}%WR · PF {pf_s} · "
                f"${st['net_pl']:.2f} |"
            )
        else:
            rows.append(
                f"| {sname} | {l['magic']} | {_session_for(sname)} | "
                f"? | No recent backtest data |"
            )
    return f"""_Auto-updated {today} by `scripts/sync_docs.py`. Source: `portfolio_v4.py` + 30-day backtest._

| Strategy | Magic | Session (IST) | Grade | Notes |
|---|---|---|---|---|
{chr(10).join(rows)}"""


# ── main ──────────────────────────────────────────────────────────────────────

def main() -> int:
    print("=" * 60)
    print("  Ultra Core — Doc Sync")
    print("=" * 60)

    print("\n[1/3] Reading PORTFOLIO_V4...")
    legs = get_portfolio_meta()
    print(f"  Found {len(legs)} legs: {', '.join(l['name'] for l in legs)}")

    print("\n[2/3] Running 30-day backtest...")
    bt = run_30day_backtest(legs)
    if bt.get("ok"):
        pf_s = f"{bt['pf']:.2f}" if bt["pf"] < 99 else "∞"
        print(f"  Result: {bt['trades']} trades | {bt['wr']:.1f}% WR | PF {pf_s} | ${bt['net_pl']:.2f}")

    print("\n[3/3] Updating docs...")
    changed = 0

    repo_guide = REPO_ROOT / "docs" / "REPO_GUIDE.md"
    battle_plan = REPO_ROOT / "docs" / "plans" / "DAILY_BATTLE_PLAN.md"
    strategy_reg = REPO_ROOT / "docs" / "research" / "STRATEGY_REGISTRY.md"

    changed += replace_block(repo_guide,     gen_repo_guide_block(legs, bt))
    changed += replace_block(battle_plan,    gen_battle_plan_block(legs, bt))
    changed += replace_block(strategy_reg,   gen_strategy_registry_block(legs, bt))

    print(f"\n{'=' * 60}")
    print(f"  Sync complete. {changed} file(s) updated.")
    print(f"{'=' * 60}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
